export const ADMIN_BLOGS_REQUEST = 'ADMIN_BLOGS_REQUEST'
export const ADMIN_BLOGS_SUCCESS = 'ADMIN_BLOGS_SUCCESS'
export const ADMIN_BLOGS_FAIL = 'ADMIN_BLOGS_FAIL'

export const ALL_BLOGS_REQUEST = 'ALL_BLOGS_REQUEST'
export const ALL_BLOGS_SUCCESS = 'ALL_BLOGS_SUCCESS'
export const ALL_BLOGS_FAIL = 'ALL_BLOGS_FAIL'

export const NEW_BLOG_REQUEST = 'NEW_BLOG_REQUEST'
export const NEW_BLOG_SUCCESS = 'NEW_BLOG_SUCCESS'
export const NEW_BLOG_RESET = 'NEW_BLOG_RESET'
export const NEW_BLOG_FAIL = 'NEW_BLOG_FAIL'

export const RANDOM_BLOG_REQUEST = 'RANDOM_BLOG_REQUEST'
export const RANDOM_BLOG_SUCCESS = 'RANDOM_BLOG_SUCCESS'
export const RANDOM_BLOG_FAIL = 'RANDOM_BLOG_FAIL'

export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST'
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS'
export const DELETE_BLOG_RESET = 'DELETE_BLOG_RESET'
export const DELETE_BLOG_FAIL = 'DELETE_BLOG_FAIL'

export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST'
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS'
export const UPDATE_BLOG_RESET = 'UPDATE_BLOG_RESET'
export const UPDATE_BLOG_FAIL = 'UPDATE_BLOG_FAIL'

export const BLOG_DETAILS_REQUEST = 'BLOG_DETAILS_REQUEST'
export const BLOG_DETAILS_SUCCESS = 'BLOG_DETAILS_SUCCESS'
export const BLOG_DETAILS_FAIL = 'BLOG_DETAILS_FAIL'

export const ADMIN_BLOG_DETAILS_REQUEST = 'ADMIN_BLOG_DETAILS_REQUEST'
export const ADMIN_BLOG_DETAILS_SUCCESS = 'ADMIN_BLOG_DETAILS_SUCCESS'
export const ADMIN_BLOG_DETAILS_FAIL = 'ADMIN_BLOG_DETAILS_FAIL'

export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST'
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS'
export const DELETE_IMAGE_RESET = 'DELETE_IMAGE_RESET'
export const DELETE_IMAGE_FAIL = 'DELETE_IMAGE_FAIL'

export const UPDATE_IMAGE_REQUEST = 'UPDATE_IMAGE_REQUEST'
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS'
export const UPDATE_IMAGE_RESET = 'UPDATE_IMAGE_RESET'
export const UPDATE_IMAGE_FAIL = 'UPDATE_IMAGE_FAIL'

export const NEW_COMMENT_REQUEST = 'NEW_COMMENT_REQUEST'
export const NEW_COMMENT_SUCCESS = 'NEW_COMMENT_SUCCESS'
export const NEW_COMMENT_RESET = 'NEW_COMMENT_RESET'
export const NEW_COMMENT_FAIL = 'NEW_COMMENT_FAIL'

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL'

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_RESET = 'DELETE_COMMENT_RESET'
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
