export const ALL_MEDIA_REQUEST = 'ALL_MEDIA_REQUEST'
export const ALL_MEDIA_SUCCESS = 'ALL_MEDIA_SUCCESS'
export const ALL_MEDIA_FAIL = 'ALL_MEDIA_FAIL'

export const MEDIA_DETAILS_REQUEST = 'MEDIA_DETAILS_REQUEST'
export const MEDIA_DETAILS_SUCCESS = 'MEDIA_DETAILS_SUCCESS'
export const MEDIA_DETAILS_FAIL = 'MEDIA_DETAILS_FAIL'

export const NEW_MEDIA_REQUEST = 'NEW_MEDIA_REQUEST'
export const NEW_MEDIA_SUCCESS = 'NEW_MEDIA_SUCCESS'
export const NEW_MEDIA_RESET = 'NEW_MEDIA_RESET'
export const NEW_MEDIA_FAIL = 'NEW_MEDIA_FAIL'

export const UPDATE_MEDIA_REQUEST = 'UPDATE_MEDIA_REQUEST'
export const UPDATE_MEDIA_SUCCESS = 'UPDATE_MEDIA_SUCCESS'
export const UPDATE_MEDIA_RESET = 'UPDATE_MEDIA_RESET'
export const UPDATE_MEDIA_FAIL = 'UPDATE_MEDIA_FAIL'

export const DELETE_MEDIA_REQUEST = 'DELETE_MEDIA_REQUEST'
export const DELETE_MEDIA_SUCCESS = 'DELETE_MEDIA_SUCCESS'
export const DELETE_MEDIA_RESET = 'DELETE_MEDIA_RESET'
export const DELETE_MEDIA_FAIL = 'DELETE_MEDIA_FAIL'

export const ALL_ORIENTATION_REQUEST = 'ALL_ORIENTATION_REQUEST'
export const ALL_ORIENTATION_SUCCESS = 'ALL_ORIENTATION_SUCCESS'
export const ALL_ORIENTATION_FAIL = 'ALL_ORIENTATION_FAIL'

export const ORIENTATION_DETAILS_REQUEST = 'ORIENTATION_DETAILS_REQUEST'
export const ORIENTATION_DETAILS_SUCCESS = 'ORIENTATION_DETAILS_SUCCESS'
export const ORIENTATION_DETAILS_FAIL = 'ORIENTATION_DETAILS_FAIL'

export const NEW_ORIENTATION_REQUEST = 'NEW_ORIENTATION_REQUEST'
export const NEW_ORIENTATION_SUCCESS = 'NEW_ORIENTATION_SUCCESS'
export const NEW_ORIENTATION_RESET = 'NEW_ORIENTATION_RESET'
export const NEW_ORIENTATION_FAIL = 'NEW_ORIENTATION_FAIL'

export const UPDATE_ORIENTATION_REQUEST = 'UPDATE_ORIENTATION_REQUEST'
export const UPDATE_ORIENTATION_SUCCESS = 'UPDATE_ORIENTATION_SUCCESS'
export const UPDATE_ORIENTATION_RESET = 'UPDATE_ORIENTATION_RESET'
export const UPDATE_ORIENTATION_FAIL = 'UPDATE_ORIENTATION_FAIL'

export const DELETE_ORIENTATION_REQUEST = 'DELETE_ORIENTATION_REQUEST'
export const DELETE_ORIENTATION_SUCCESS = 'DELETE_ORIENTATION_SUCCESS'
export const DELETE_ORIENTATION_RESET = 'DELETE_ORIENTATION_RESET'
export const DELETE_ORIENTATION_FAIL = 'DELETE_ORIENTATION_FAIL'

export const ALL_ARTISTS_REQUEST = 'ALL_ARTISTS_REQUEST'
export const ALL_ARTISTS_SUCCESS = 'ALL_ARTISTS_SUCCESS'
export const ALL_ARTISTS_FAIL = 'ALL_ARTISTS_FAIL'

export const ARTIST_DETAILS_REQUEST = 'ARTIST_DETAILS_REQUEST'
export const ARTIST_DETAILS_SUCCESS = 'ARTIST_DETAILS_SUCCESS'
export const ARTIST_DETAILS_FAIL = 'ARTIST_DETAILS_FAIL'

export const NEW_ARTIST_REQUEST = 'NEW_ARTIST_REQUEST'
export const NEW_ARTIST_SUCCESS = 'NEW_ARTIST_SUCCESS'
export const NEW_ARTIST_RESET = 'NEW_ARTIST_RESET'
export const NEW_ARTIST_FAIL = 'NEW_ARTIST_FAIL'

export const UPDATE_ARTIST_REQUEST = 'UPDATE_ARTIST_REQUEST'
export const UPDATE_ARTIST_SUCCESS = 'UPDATE_ARTIST_SUCCESS'
export const UPDATE_ARTIST_RESET = 'UPDATE_ARTIST_RESET'
export const UPDATE_ARTIST_FAIL = 'UPDATE_ARTIST_FAIL'

export const DELETE_ARTIST_REQUEST = 'DELETE_ARTIST_REQUEST'
export const DELETE_ARTIST_SUCCESS = 'DELETE_ARTIST_SUCCESS'
export const DELETE_ARTIST_RESET = 'DELETE_ARTIST_RESET'
export const DELETE_ARTIST_FAIL = 'DELETE_ARTIST_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'