export const ADMIN_FRIENDS_REQUEST = 'ADMIN_FRIENDS_REQUEST'
export const ADMIN_FRIENDS_SUCCESS = 'ADMIN_FRIENDS_SUCCESS'
export const ADMIN_FRIENDS_FAIL = 'ADMIN_FRIENDS_FAIL'

export const ALL_FRIENDS_REQUEST = 'ALL_FRIENDS_REQUEST'
export const ALL_FRIENDS_SUCCESS = 'ALL_FRIENDS_SUCCESS'
export const ALL_FRIENDS_FAIL = 'ALL_FRIENDS_FAIL'

export const NEW_FRIEND_REQUEST = 'NEW_FRIEND_REQUEST'
export const NEW_FRIEND_SUCCESS = 'NEW_FRIEND_SUCCESS'
export const NEW_FRIEND_RESET = 'NEW_FRIEND_RESET'
export const NEW_FRIEND_FAIL = 'NEW_FRIEND_FAIL'

export const DELETE_FRIEND_REQUEST = 'DELETE_FRIEND_REQUEST'
export const DELETE_FRIEND_SUCCESS = 'DELETE_FRIEND_SUCCESS'
export const DELETE_FRIEND_RESET = 'DELETE_FRIEND_RESET'
export const DELETE_FRIEND_FAIL = 'DELETE_FRIEND_FAIL'

export const UPDATE_FRIEND_REQUEST = 'UPDATE_FRIEND_REQUEST'
export const UPDATE_FRIEND_SUCCESS = 'UPDATE_FRIEND_SUCCESS'
export const UPDATE_FRIEND_RESET = 'UPDATE_FRIEND_RESET'
export const UPDATE_FRIEND_FAIL = 'UPDATE_FRIEND_FAIL'

export const FRIEND_DETAILS_REQUEST = 'FRIEND_DETAILS_REQUEST'
export const FRIEND_DETAILS_SUCCESS = 'FRIEND_DETAILS_SUCCESS'
export const FRIEND_DETAILS_FAIL = 'FRIEND_DETAILS_FAIL'

export const ADMIN_FRIEND_DETAILS_REQUEST = 'ADMIN_FRIEND_DETAILS_REQUEST'
export const ADMIN_FRIEND_DETAILS_SUCCESS = 'ADMIN_FRIEND_DETAILS_SUCCESS'
export const ADMIN_FRIEND_DETAILS_FAIL = 'ADMIN_FRIEND_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
