export const ADMIN_PAGES_REQUEST = 'ADMIN_PAGES_REQUEST'
export const ADMIN_PAGES_SUCCESS = 'ADMIN_PAGES_SUCCESS'
export const ADMIN_PAGES_FAIL = 'ADMIN_PAGES_FAIL'

export const ALL_PAGES_REQUEST = 'ALL_PAGES_REQUEST'
export const ALL_PAGES_SUCCESS = 'ALL_PAGES_SUCCESS'
export const ALL_PAGES_FAIL = 'ALL_PAGES_FAIL'

export const NEW_PAGE_REQUEST = 'NEW_PAGE_REQUEST'
export const NEW_PAGE_SUCCESS = 'NEW_PAGE_SUCCESS'
export const NEW_PAGE_RESET = 'NEW_PAGE_RESET'
export const NEW_PAGE_FAIL = 'NEW_PAGE_FAIL'

export const DELETE_PAGE_REQUEST = 'DELETE_PAGE_REQUEST'
export const DELETE_PAGE_SUCCESS = 'DELETE_PAGE_SUCCESS'
export const DELETE_PAGE_RESET = 'DELETE_PAGE_RESET'
export const DELETE_PAGE_FAIL = 'DELETE_PAGE_FAIL'

export const UPDATE_PAGE_REQUEST = 'UPDATE_PAGE_REQUEST'
export const UPDATE_PAGE_SUCCESS = 'UPDATE_PAGE_SUCCESS'
export const UPDATE_PAGE_RESET = 'UPDATE_PAGE_RESET'
export const UPDATE_PAGE_FAIL = 'UPDATE_PAGE_FAIL'

export const PAGE_DETAILS_REQUEST = 'PAGE_DETAILS_REQUEST'
export const PAGE_DETAILS_SUCCESS = 'PAGE_DETAILS_SUCCESS'
export const PAGE_DETAILS_FAIL = 'PAGE_DETAILS_FAIL'

export const ADMIN_PAGE_DETAILS_REQUEST = 'ADMIN_PAGE_DETAILS_REQUEST'
export const ADMIN_PAGE_DETAILS_SUCCESS = 'ADMIN_PAGE_DETAILS_SUCCESS'
export const ADMIN_PAGE_DETAILS_FAIL = 'ADMIN_PAGE_DETAILS_FAIL'

export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST'
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS'
export const DELETE_IMAGE_RESET = 'DELETE_IMAGE_RESET'
export const DELETE_IMAGE_FAIL = 'DELETE_IMAGE_FAIL'

export const UPDATE_IMAGE_REQUEST = 'UPDATE_IMAGE_REQUEST'
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS'
export const UPDATE_IMAGE_RESET = 'UPDATE_IMAGE_RESET'
export const UPDATE_IMAGE_FAIL = 'UPDATE_IMAGE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
