export const ADMIN_PAINTERS_REQUEST = 'ADMIN_PAINTERS_REQUEST'
export const ADMIN_PAINTERS_SUCCESS = 'ADMIN_PAINTERS_SUCCESS'
export const ADMIN_PAINTERS_FAIL = 'ADMIN_PAINTERS_FAIL'

export const ALL_PAINTERS_REQUEST = 'ALL_PAINTERS_REQUEST'
export const ALL_PAINTERS_SUCCESS = 'ALL_PAINTERS_SUCCESS'
export const ALL_PAINTERS_FAIL = 'ALL_PAINTERS_FAIL'

export const NEW_PAINTER_REQUEST = 'NEW_PAINTER_REQUEST'
export const NEW_PAINTER_SUCCESS = 'NEW_PAINTER_SUCCESS'
export const NEW_PAINTER_RESET = 'NEW_PAINTER_RESET'
export const NEW_PAINTER_FAIL = 'NEW_PAINTER_FAIL'

export const DELETE_PAINTER_REQUEST = 'DELETE_PAINTER_REQUEST'
export const DELETE_PAINTER_SUCCESS = 'DELETE_PAINTER_SUCCESS'
export const DELETE_PAINTER_RESET = 'DELETE_PAINTER_RESET'
export const DELETE_PAINTER_FAIL = 'DELETE_PAINTER_FAIL'

export const UPDATE_PAINTER_REQUEST = 'UPDATE_PAINTER_REQUEST'
export const UPDATE_PAINTER_SUCCESS = 'UPDATE_PAINTER_SUCCESS'
export const UPDATE_PAINTER_RESET = 'UPDATE_PAINTER_RESET'
export const UPDATE_PAINTER_FAIL = 'UPDATE_PAINTER_FAIL'

export const PAINTER_DETAILS_REQUEST = 'PAINTER_DETAILS_REQUEST'
export const PAINTER_DETAILS_SUCCESS = 'PAINTER_DETAILS_SUCCESS'
export const PAINTER_DETAILS_FAIL = 'PAINTER_DETAILS_FAIL'

export const ADMIN_PAINTER_DETAILS_REQUEST = 'ADMIN_PAINTER_DETAILS_REQUEST'
export const ADMIN_PAINTER_DETAILS_SUCCESS = 'ADMIN_PAINTER_DETAILS_SUCCESS'
export const ADMIN_PAINTER_DETAILS_FAIL = 'ADMIN_PAINTER_DETAILS_FAIL'

export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST'
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS'
export const DELETE_IMAGE_RESET = 'DELETE_IMAGE_RESET'
export const DELETE_IMAGE_FAIL = 'DELETE_IMAGE_FAIL'

export const UPDATE_IMAGE_REQUEST = 'UPDATE_IMAGE_REQUEST'
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS'
export const UPDATE_IMAGE_RESET = 'UPDATE_IMAGE_RESET'
export const UPDATE_IMAGE_FAIL = 'UPDATE_IMAGE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
